feat: Add Popover Close and minor type improvment
huntabyte/shadcn-svelte pull request #848
Opened 2024-03-03 05:07 UTC by jkyamog

I needed to close the popover after the user clicks a button in the popover content.  That button would fire an event and does something.  However it would not close the popover.  By adding the existing popover close as a child its now possible to do this.

Some minor improvement to input component useful to export FormInputEvent for other TS code to be properly typed.

`const handleChange = (event: FormInputEvent<Event>) => {...}`

2024-03-03 22:39 UTC, huntabyte requested changes
Revert the changes to the examples and this will be good to merge.

2024-03-03 22:39 UTC, huntabyte commented on apps/www/src/lib/registry/new-york/example/popover-demo.svelte
> +	<Popover.Close asChild let:builder>
We don't need this in the example.

2024-03-03 22:39 UTC, huntabyte commented on apps/www/src/lib/registry/default/example/popover-demo.svelte
> +	<Popover.Close asChild let:builder>
We don't need this in the example.

2024-03-03 23:56 UTC, jkyamog commented on apps/www/src/lib/registry/new-york/example/popover-demo.svelte
> +	<Popover.Close asChild let:builder>
removed from example.  thanks.

2024-03-03 23:56 UTC, jkyamog commented on apps/www/src/lib/registry/default/example/popover-demo.svelte
> +	<Popover.Close asChild let:builder>
removed from example.  thanks.

2024-03-04 04:44 UTC, huntabyte approved these changes
Thank you!

2024-03-04 05:12 UTC, jkyamog commented
@huntabyte Thank you too for maintaining this code base.   Just checked the warning on the build about prettier, I did a quick npx prettier on my local checkout.  It should now be ok, seems unrelated carousel components has some small issue as well.

2024-03-04 14:50 UTC, merged